### ISSUE TITLE
Move blockNumber into transaction schema

### ISSUE THREAD

**Issue by ben-chain** [plasma-group/plasma-utils#23]
**Is your feature request related to a problem? Please describe.**
Right now, the transaction schema includes a `block` field which lists the plasma block height at which the transfer is valid.  However, since this is a list of transfers, it is redundant to have the block in each transfer.

**Describe the solution you'd like**
Move the `blockNumber` into the transaction schema and omit it from `TransferRecords`.

**Comment by kfichter** [comment]
:+1: that makes more sense than referencing the block number in each transfer.

**Comment by ben-chain** [comment]
Closed by commit 3b658ede4b77a6d345a171cb7e47c026cee76867
