### ISSUE TITLE
Define encoding field order

### ISSUE THREAD

**Issue by ben-chain** [plasma-group/plasma-utils#35]
**Is your feature request related to a problem? Please describe.**
I've run into a problem where I need to define the ordering of elements in the encoding.  This is because 

Oddly, it almost seems like the decoding and encoding order is not the same when I did this.  I switched the order of the fields in the schema file in the PR I submitted, and the change required me to switch the order of the hardcoded encoding string to get tests to pass.  BUT, when you call `transferProof.encoded`, that encoding is different than the original one fed in...

**Describe the solution you'd like**
`TransferProofs` have only one element which is variable sized, I need it to go last so that the start positions of all other elements are fixed.  The other orderings don't matter.

**Describe alternatives you've considered**
I could probably get away with doing the weird calculation if we have to have the array in the middle, but it's a bad hack which gets reallly gnarly for variable-depth `TransactionProofs`.

I know you use property/key iterations a lot in the code, and [this](https://stackoverflow.com/questions/5525795/does-javascript-guarantee-object-property-order) worries me that doing this ordering is tough.  If we had to do something janky like taking advantage of node processing by alphabetical order and renaming the fields, I could live with that if it got a quick temp solution.

**Comment by ben-chain** [comment]
To replicate some weird related behavior, go to `debugger` at line `223` of my most recent push in the my fork of `plasma-contracts`, and compare `encodedTransferProof` to `transferProof.encoded`.  Different ordering, despite `encodedTransferProof` being copy-pasted directly from passing tests in my PR to `plasma-utils`.

**Comment by kfichter** [comment]
Hmm, I have an idea to fix this. Will report back in about an hour.

**Comment by kfichter** [comment]
Update: NVM, let's chat by phone later today. There's probably an easy fix to this.

**Comment by ben-chain** [comment]
Fixed--just forgot to npm update to reflect new utils ordering!
